### PR TITLE
Quarkus serialization integration

### PR DESCRIPTION
**Pull request by andreaTP**
I integrated the generated `ApiClient` to better play with Quarkus applications, but this is, likely, not the "final shape" of the API. I'm super happy to receive feedback and ideas on the various elements of this PR, especially:

- The "default" Jackson ser/deser relies on a "global" `ObjectMapper` since the generated `ApiClient` constructor API doesn't accept additional parameters. An alternative design would be to register ser/deser in/from the `RequestAdapter`. But those changes highly depend on the result of: https://github.com/microsoft/kiota/issues/3796 cc. @baywet , more practically: if we remove the ser/deser static initialization, do we have any guidance? Or are we on our own to design how it will work?
- I found it a bit cumbersome to play with the `quarkus-arc` CDI from the generated code, especially mixing and matching constructor arguments and injected fields. I ended up re-writing the generated `ApiClient` constructor from the Quarkus extension to accept a plain additional parameter and build on top of that from the user-code: https://github.com/kiota-community/kiota-java-extra/pull/58/files#diff-781635c5ea2c546dd924d5ba383da03fe8cd2c720a0709881afcc35f29111bf6R22 I would be glad if @maxandersen can provide additional guidance and/or indicate someone with a deeper Quarkus CDI experience to end up with the best possible design of this integration.
- Re-writing generated code from the Quarkus extension is extremely fragile and we should move away from this pattern ASAP, also, the generated code is going to be dependent on Jackson in this case which is not desirable from an "ecosystem" POV.

Happy to hear more thoughts!

### CODE REVIEW

**Comment by baywet** [comment]
I don't have the whole context on what we're trying to achieve here.
But assuming we just want kiota customers to be able to use different implementations of serialization/deserialization, you could instruct them (provide a snippet) to use these dependencies instead, and initialize the request adapter with the parameters for parse node/serialization writer factories.

**Comment by andreaTP** [comment]
Thanks a lot for chipping in @baywet, as always.

> we just want kiota customers to be able to use different implementations of serialization/deserialization

Correct, that's the end goal, but can be achieved in multiple ways:
1. each "integrator" like myself comes up with a different pattern
2. we provide "something"(e.g.: an interface in "Abstractions") and we document it in Kiota so that users will have the same kind of experience across different integrations
3. we can change the current implementation to be compatible with the additional interface in abstraction instead of being hard-coded in the generated code
4. more?

Even if 1 is always feasible, not giving a guideline might hit back in terms of "experience consistency" and can fracture the ecosystem in the longer run; I'm convinced that, with a little bit of ahead thinking, very little is needed to do a bit better.

**Comment by baywet** [comment]
can you expand on 2 & 3 please? I'm not sure I'm envisioning what you're referring to.

**Comment by baywet** [comment]
Thanks for the additional context here.

> the generated ApiClient class, by default, can call this delegate (DefaultSerializationRegistration.register()) instead of expanding all of the relevant code in the constructor of the client (which is currently mixing some concerns)

Isn't that exactly what the ApiClient is doing today with ApiClientBUilder? or did I miss something?

> One possibility would be to add an overloaded constructor to the ApiClient class that will take an additional parameter as a SerializationRegistration instance

In the very early days it was here, but it was deemed too complicated and not portable enough, we also wanted to keep most configuration in the request adapter. Hence the current design. I don't think we'll be going back here, only forward.

**Comment by andreaTP** [comment]
> Isn't that exactly what the ApiClient is doing today with ApiClientBUilder? or did I miss something?

Moving to the `ApiClientBuilder` is a possibility for sure, but we lack have a way to define a custom `ApiClientBuilder` in user-land and use it.

> Hence the current design. I don't think we'll be going back here, only forward.

I'm fine with this, what about moving this registration logic down the chain in the `RequestAdapter` too?

**Comment by baywet** [comment]
sorry, I'm still unclear how a third party implementation of serialization (for XML let's say) will auto-register itself without using some kind of reflection and without asking the consumer to do it manually and without having it done as part of the generated client?
How is abstractions' registry going to be aware of an implementation of ParseNode/SerializationWriter factory?
As far as I know the only languages where this might be possible is JavaScript and maybe Ruby because they can declare self-executing functions. And that still requires people importing the function in TypeScript so it doesn't get trimmed out.

**Comment by andreaTP** [comment]
Let's try to drill down a possible implementation in `RequestAdapter`:

- we add to `RequestAdapter` an abstract method `() -> register()`
- in the generated code the constructor of `ApiClient` will call `adapter.register()` instead of the multiple `ApiClientBuilder....` calls - the CLI does not need to know the Ser/Deser class names anymore
- Each implementation of `RequestAdapter` can decide how to handle the Ser/Deser:
  - in the default implementation we can keep something similar to the current implementation
  - it becomes possible to "bundle" libraries together, for example, the VertX client can directly register the Jackson ser/deser depending on the relevant artifact
  
For completeness, I do believe that we can already remove the usage of reflection in the `ApiClientBuilder` class, I'll try to submit a proposal.

**Comment by baywet** [comment]
I see what you mean now, thanks for your patience.

I think we could ultimately remove singleton registries all together, which should make things thread safe (r) and clean up the design. This would also bring alignment with how the backing store works in terms of enabling it on the serialization/parse node factories. (method on the request adapter) The requirement would be for request adapters to also provide access to the registries (via getters) and most likely to change the constructors to accept registries instead of factories.

Here are a couple of drawbacks I can see:
- This is a major design change we should carry across languages.
- This design change would be breaking for stable languages (adding a couple of methods to an interface)

And it still leaves me with one question:
I'm assuming in that scenario, people implementing their own request adapters would tightly couple them to serialization implementations so that users of the clients don't have to set all of this up. Is that correct?

**Comment by baywet** [comment]
Right, I think we should queue that for a v2, but wouldn't be able to have that in v1 as I don't think there's a non-breaking way around adding methods in interfaces. And staggering the change across multiple languages and/or splitting interfaces to avoid breaking changes would kind of defeat the purpose here.
Would you mind creating an issue on kiota main recapping the design changes please? (adding getters and setters to the registries on the request adapter, changing default request adapters constructor parameters to accept registries instead of factories, changing the code-gen to use that instead of the static registries, cleaning up the static registries)

**Comment by andreaTP** [comment]
Fair, I'll do the write-up in the next few days 👍 , we probably want to start the conversation about "what should be done to roll out the next major release"? (as a separate item).

For this PR, I'll turn the code around to target the agreed solution, so that:

- we can start experimenting with the new design and, possibly, identify issues with it
- minimize the number of breaking changes for Quarkus users when this new design becomes a reality.

**Comment by andreaTP** [comment]
Hey @geoand ! Thanks for chipping in!
It's a public holiday here and I'll elaborate more on Mon.

You will have an idea of what is going on when running the quarkus integration tests:

- we have a library for Json ser/deser
- we generate code that will be using the library
- we want to be able to use the generated code injecting the default ObjectMapper

We are pretty free in turning things around, and I would like to end up with a Quarkus setup as idiomatic as possible.
Maybe is easier/faster with a quick sync call somewhere next week.

**Comment by geoand** [comment]
> Maybe is easier/faster with a quick sync call somewhere next week.

Sure yeah

**Comment by andreaTP** [comment]
Thanks @geoand for the suggestions, it works swiftly (they are in the generated code not committed).

This is ready for review, if anyone wanna take a look `mvn clean install` and look at the generated code in `/quarkus/integration-tests/`

**Pull request merged**
